project:
  type: website
  output-dir: ../docs


website:
  page-navigation: true
  search: false
  page-footer:
    border: false
    background: transparent
    foreground: DimGray
    #left: Left content
    #right: Right content
  navbar:
    background: transparent
    pinned: true
    left:
      - file: index.qmd
        text: Home
      - file: "human.qmd#intro"
        text: Introduction
      - text: Analysis
        menu:
        - text: Exploratory Data Analysis
          href: "human.qmd#analysis"
        - text: Feature Engineering
          href: "human.qmd#feature"
        - text: Modeling
          href: "human.qmd#model"
        - text: Results
          href: "human.qmd#results"
      - text: Conclusion
        href: "human.qmd#conclusion"

    right:
      - icon: github
        href: https://github.com/chaishekar/HAR-Neural-Network-Project


        

format:
  html:
    theme: 
      - styles.scss
    toc: false

editor: visual
